// Commitlint flat config — enforces Conventional Commits for the template.
// Shared config sourced from @commitlint/config-conventional, which permits the
// commit types used across this repo (feat, fix, chore, test, docs, refactor, ci,
// style, perf, build, revert) plus the default scopes and rules it ships with.
//
// In addition, a custom "no-co-authored-by" rule rejects Co-Authored-By and
// AI-attribution trailers in the body or footer. This config is shared by both
// the local husky hook (.husky/commit-msg -> commitlint --edit) and the CI
// `commitlint` job, so local and remote enforcement stay consistent (MA-3).
import type { UserConfig } from "@commitlint/types";

const NO_AUTHORED_BY =
  /(^|\n)(Co-Authored-By|Co-authored-by)\s*:\s*[^\n]*\S|(^|\n)(Generated with|Generated by|Authored by|Written by|Created by|Made with|Powered by)\s*:?\s*[^\n]*\S/i;

const config: UserConfig = {
  extends: ["@commitlint/config-conventional"],
  plugins: [
    {
      rules: {
        "no-co-authored-by": (parsed, _when, value) => {
          const source = [parsed?.header, parsed?.body, parsed?.footer].filter(Boolean).join("\n");
          const re = value instanceof RegExp ? value : NO_AUTHORED_BY;
          if (!re.test(source)) {
            return [true];
          }
          return [
            false,
            "commit message must not contain a Co-Authored-By or AI-attribution trailer",
          ];
        },
      },
    },
  ],
  rules: {
    "no-co-authored-by": [2, "never", NO_AUTHORED_BY],
  },
};

export default config;
